name: Build Prod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm i -g pnpm
    - run: pnpm install --registry=https://registry.npmmirror.com
    - run: pnpm run build
